#!/bin/bash
#
# @author    Volker Theile <volker.theile@openmediavault.org>
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2017 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

declare -i httpport=0
declare -i httpsport=0

XPATH_NAME="domoticz"
XPATH="/config/services/${XPATH_NAME}"
OVERRIDE_CONF_DIR="/etc/systemd/system/domoticz.service.d"
OVERRIDE_CONF="${OVERRIDE_CONF_DIR}/override.conf"

enable=$(omv_config_get "${XPATH}/enable")
httpenable=$(omv_config_get "${XPATH}/httpenable")
httpport=$(omv_config_get "${XPATH}/httpport")
httpsenable=$(omv_config_get "${XPATH}/httpsenable")
httpsport=$(omv_config_get "${XPATH}/httpsport")

if [ "${httpenable}" = "0" ] && [ "${httpsenable}" = "0" ]; then
    http=" -www 8077"
    https=" -sslwww 0"
else
    if [ "${httpenable}" = "1" ]; then
        if [ ${httpport} -le 0 ]; then
            httpport=8077
        fi
        http=" -www ${httpport}"
    else
        http=" -www 0"
    fi

    if [ "${httpsenable}" = "1" ]; then
        if [ ${httpsport} -le 0 ]; then
            httpsport=8078
        fi
        https=" -sslwww ${httpsport}"
    else
        https=" -sslwww 0"
    fi
fi

# create directory
mkdir -p "${OVERRIDE_CONF_DIR}"

# Create override conf file
cat <<EOF > ${OVERRIDE_CONF}
[Service]
ExecStart=
ExecStart=/opt/domoticz/domoticz -daemon${http}${https}
EOF

# Reload daemon
systemctl daemon-reload

if [ "${enable}" = "1" ]; then
    systemctl restart domoticz.service
fi